/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.servico;

import DAOImplementation.ServicoDAOImpl;
import java.util.HashMap;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;
import javax.swing.JOptionPane;
import models.Animal;
import models.Cliente;
import models.Promocao;
import models.Servico;

/**
 *
 * @author arthu
 */
public class AlterarServicoJD extends javax.swing.JDialog {

    private ServicoDAOImpl servicoDAOImpl;
    private HashMap<Integer, Cliente> lClientes;
    private HashMap<Integer, Promocao> lPromocoes;
    private HashMap<Integer, Animal> lAnimais;

    public AlterarServicoJD(java.awt.Frame parent, boolean modal, ServicoDAOImpl servicoDAOImpl, HashMap<Integer, Cliente> lClientes, HashMap<Integer, Promocao> lPromocoes, HashMap<Integer, Animal> lAnimais) {
        super(parent, modal);
        this.servicoDAOImpl = servicoDAOImpl;
        this.lClientes = lClientes;
        this.lPromocoes = lPromocoes;
        this.lAnimais = lAnimais;
        initComponents();
        setTitle("Alterar Serviço");

        Integer[] clientesKeys = lClientes.keySet().toArray(new Integer[0]);
        String[] clienteList = new String[clientesKeys.length];
        for (int i = 0; i < clientesKeys.length; i++) {
            clienteList[i] = String.valueOf(clientesKeys[i]);
        }
        clientesJL.setListData(clienteList);
        clientesJL.setSelectedIndex(-1);

        Integer[] promocoesKeys = lPromocoes.keySet().toArray(new Integer[0]);
        String[] promocaoList = new String[promocoesKeys.length];
        for (int i = 0; i < promocoesKeys.length; i++) {
            promocaoList[i] = String.valueOf(promocoesKeys[i]);
        }
        promocoesJL.setListData(promocaoList);
        promocoesJL.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarServicoBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataTF = new javax.swing.JTextField();
        horaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeServicoTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesJL = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        promocoesJL = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        animaisJL = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Funcionário");

        alterarServicoBTN.setText("Alterar");
        alterarServicoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarServicoBTNActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        jLabel6.setText("Digite o ID e as informações e aperte em Alterar");

        jLabel2.setText("Cliente");

        jLabel7.setText("Data");

        jLabel8.setText("Hora");

        jLabel10.setText("Preço");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jLabel3.setText("Promoção");

        jLabel12.setText("Animal");

        jLabel1.setText("Serviço");

        clientesJL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        clientesJL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clientesJLValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(clientesJL);

        promocoesJL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(promocoesJL);

        animaisJL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(animaisJL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(alterarServicoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeServicoTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(81, 81, 81)
                                            .addComponent(jLabel3)
                                            .addGap(63, 63, 63)
                                            .addComponent(jLabel12))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(0, 76, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(precoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(horaTF)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeServicoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel12))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterarServicoBTN)
                            .addComponent(sair)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarServicoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarServicoBTNActionPerformed
        if (clientesJL.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Cliente não pode ser nulo");
            return;
        }
        Integer idCliente = Integer.valueOf(clientesJL.getSelectedValue());

        if (animaisJL.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Animal não pode ser nulo");
            return;
        }
        Integer idAnimal = Integer.valueOf(animaisJL.getSelectedValue());

        Integer idPromocao = null;
        if (promocoesJL.getSelectedIndex() == -1) {
            idPromocao = Integer.valueOf(promocoesJL.getSelectedValue());
        }

        DateTimeFormatter formatterDT = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataTF.getText(), formatterDT);
        LocalTime hora = LocalTime.parse(horaTF.getText());

        Object[] args = new Object[]{nomeServicoTF.getText(), Double.valueOf(precoTF.getText()), idPromocao, data, hora, idAnimal, idCliente};
        if (!servicoDAOImpl.altera(Integer.valueOf(idTF.getText()), args)) {
            JOptionPane.showMessageDialog(null, String.format("Serviço %s não alterado", idTF.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Serviço alterado");
        }

        nomeServicoTF.setText(null);
        precoTF.setText(null);
        dataTF.setText(null);
        horaTF.setText(null);
        clientesJL.setSelectedIndex(-1);
        promocoesJL.setSelectedIndex(-1);
        animaisJL.setSelectedIndex(-1);
    }//GEN-LAST:event_alterarServicoBTNActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void clientesJLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientesJLValueChanged
        Cliente c = lClientes.get(Integer.valueOf(clientesJL.getSelectedValue()));
        animaisJL.setListData(c.infoAnimal());
        animaisJL.setSelectedIndex(-1);
    }//GEN-LAST:event_clientesJLValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarServicoBTN;
    private javax.swing.JList<String> animaisJL;
    private javax.swing.JList<String> clientesJL;
    private javax.swing.JTextField dataTF;
    private javax.swing.JTextField horaTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomeServicoTF;
    private javax.swing.JTextField precoTF;
    private javax.swing.JList<String> promocoesJL;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
