/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.animal;

import controllers.AnimalController;
import controllers.ClienteController;
import java.util.Objects;
import javax.swing.JOptionPane;
import models.Animal;
import models.Cliente;

/**
 *
 * @author arthu
 */
public class AdicionarAnimalJD extends javax.swing.JDialog {

    private AnimalController ac;
    private ClienteController cc;

    public AdicionarAnimalJD(java.awt.Frame parent, boolean modal, AnimalController ac, ClienteController cc) {
        super(parent, modal);
        this.ac = ac;
        this.cc = cc;
        initComponents();
        setTitle("Adicionar Animal");

        Integer[] donosKeys = cc.relatorio().keySet().toArray(new Integer[0]);
        String[] listData = new String[donosKeys.length];
        for (int i = 0; i < donosKeys.length; i++) {
            listData[i] = String.valueOf(donosKeys[i]);
        }
        donoJL.setListData(listData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        especieTF = new javax.swing.JTextField();
        adicionarAnimalBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donoJL = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        resposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Funcionário");

        adicionarAnimalBTN.setText("Adicionar");
        adicionarAnimalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAnimalBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Espécie");

        jLabel5.setText("Nome");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jLabel6.setText("Digite todos os campos do animal e aperte Adicionar");

        donoJL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(donoJL);

        jLabel2.setText("Dono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionarAnimalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(nomeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(especieTF))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(resposta))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta)
                .addGap(19, 19, 19)
                .addComponent(adicionarAnimalBTN)
                .addGap(12, 12, 12)
                .addComponent(sair)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarAnimalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAnimalBTNActionPerformed
        Cliente dono = null;
        if (!donoJL.isSelectionEmpty()) {
            dono = cc.consulta(Integer.valueOf(donoJL.getSelectedValue()));
        }

        Animal animal = new Animal(dono, nomeTF.getText(), especieTF.getText());

        if (ac.adicionar(animal)) {
            donoJL.setSelectedIndex(-1);
            nomeTF.setText(null);
            especieTF.setText(null);
            resposta.setText(String.format("Animal adicionado com ID: %d", animal.getIdAnimal()));
            JOptionPane.showMessageDialog(null, "Animal cadastrado");
        } else {
            donoJL.setSelectedIndex(-1);
            resposta.setText(null);
            JOptionPane.showMessageDialog(null, "Animal não cadastrado");
        }

        if (!Objects.isNull(dono)) {
            dono.addAnimal(animal);
        }
    }//GEN-LAST:event_adicionarAnimalBTNActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAnimalBTN;
    private javax.swing.JList<String> donoJL;
    private javax.swing.JTextField especieTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel resposta;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
